print("pip install mysql-connector-python")
print("pip install pandas")
print("pip install numpy")
print("pip install matplotlib")
print("pip install auto-py-to-exe")
print("python -m auto_py_to_exe")
